// <auto-generated> - Template:DTO, Version:2.0, Id:0d58c309-4b48-4464-819d-83c9c87cf463
using System;
namespace CGHClientServer1.DTO.CSC
{
	public partial class Country
	{
		public Country()
		{
			InitializePartial();
		}

		public Guid CountryId { get; set; } // Primary key
		public string Name { get; set; }
		public virtual System.Collections.Generic.ICollection<State> States { get; set; } // Many to many mapping

		partial void InitializePartial();

	}
}
