// <auto-generated> - Template:DTO, Version:2.0, Id:0d58c309-4b48-4464-819d-83c9c87cf463
using System;
namespace CGHClientServer1.DTO.CSC
{
	public partial class State
	{
		public State()
		{
			InitializePartial();
		}

		public Guid StateId { get; set; } // Primary key
		public Guid CountryId { get; set; }
		public string Name { get; set; }
		public virtual System.Collections.Generic.ICollection<City> Cities { get; set; } // Many to many mapping
		public virtual Country Country { get; set; } // One to One mapping

		partial void InitializePartial();

	}
}
