// <auto-generated> - Template:WebApiController, Version:2.0, Id:4f4c0cb1-134c-477a-b796-0ea82a911d33
using AutoMapper;
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Http.Routing;
using Marvin.JsonPatch;
using cghEnums = CodeGenHero.Repository.Enums;
using coreEnums = CodeGenHero.Core.Enums;
using CodeGenHero.DataService;
using CodeGenHero.Repository;
using CodeGenHero.Repository.AutoMapper;
using CodeGenHero.WebApi;
using CGHClientServer1.Repository.Interface;
using dtoCSC = CGHClientServer1.DTO.CSC;
using entCSC = CGHClientServer1.DB.Entities;

namespace CGHClientServer1.API.Controllers.CSC
{
	public partial class CitiesCSCController : CSCBaseApiController
	{
			private const string GET_LIST_ROUTE_NAME = "CitiesCSCList";
			private const int maxPageSize = 100;
			private GenericFactory<entCSC.City, dtoCSC.City> _factory;

		public CitiesCSCController(ILogger<CitiesCSCController> log, ICSCRepository repository, IMapper mapper)
		: base(log, repository)
		{
			_factory = new GenericFactory<entCSC.City, dtoCSC.City>(mapper);
		}

		[HttpDelete]
		[VersionedRoute(template: "Cities/{cityId}", allowedVersion: 1)]
		public async Task<IHttpActionResult> Delete(Guid cityId)
		{
			try
			{
				if (!base.OnActionExecuting(out HttpStatusCode httpStatusCode, out string message)) { return Content(httpStatusCode, message); }

				var result = await Repo.Delete_CityAsync(cityId);

				if (result.Status == cghEnums.RepositoryActionStatus.Deleted)
				{
					return StatusCode(HttpStatusCode.NoContent);
				}
				else if (result.Status == cghEnums.RepositoryActionStatus.NotFound)
				{
					return NotFound();
				}

				Log.LogWarning(eventId: (int)coreEnums.EventId.Warn_WebApi,
					exception: result.Exception,
					message: "Unable to delete object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				return BadRequest();
			}
			catch (Exception ex)
			{
				Log.LogError(eventId: (int)coreEnums.EventId.Exception_WebApi,
					exception: ex,
					message: "Unable to delete object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}

		[HttpGet]
		[VersionedRoute(template: "Cities", allowedVersion: 1, Name = GET_LIST_ROUTE_NAME)]
		#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
		public async Task<IHttpActionResult> Get(string sort = null,
		string fields = null, string filter = null, int page = 1, int pageSize = maxPageSize)
		#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
		{
			try
			{
				if (!base.OnActionExecuting(out HttpStatusCode httpStatusCode, out string message)) { return Content(httpStatusCode, message); }

				var fieldList = GetListByDelimiter(fields);
				bool childrenRequested = false; // TODO: set this based upon actual fields requested.

				var filterList = GetListByDelimiter(filter);
				var dbItems = Repo.GetQueryable_City().AsNoTracking();
				RunCustomLogicAfterGetQueryableList(ref dbItems, ref filterList);
				dbItems = dbItems.ApplyFilter(filterList);
				dbItems = dbItems.ApplySort(sort ?? (typeof(entCSC.City).GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance)).First().Name);

				if (pageSize > maxPageSize)
				{ // ensure the page size isn't larger than the maximum.
					pageSize = maxPageSize;
				}

				var urlHelper = new UrlHelper(Request);
				PageData paginationHeader = BuildPaginationHeader(urlHelper, GET_LIST_ROUTE_NAME, page: page, totalCount: dbItems.Count(), pageSize: pageSize, sort: sort);
				HttpContext.Current.Response.Headers.Add("X-Pagination", Newtonsoft.Json.JsonConvert.SerializeObject(paginationHeader));

				// return result
				return Ok(dbItems
				.Skip(pageSize * (page - 1))
				.Take(pageSize)
				.ToList()
				.Select(x => _factory.CreateDataShapedObject(x, fieldList, childrenRequested)));
			}
			catch (Exception ex)
			{
				Log.LogError(eventId: (int)coreEnums.EventId.Exception_WebApi,
					exception: ex,
					message: "Unable to get object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}

		[HttpGet]
		[VersionedRoute(template: "Cities/{cityId}/{numChildLevels:int=0}", allowedVersion: 1)]
		public async Task<IHttpActionResult> Get(Guid cityId, int numChildLevels)
		{
			try
			{
				if (!base.OnActionExecuting(out HttpStatusCode httpStatusCode, out string message)) { return Content(httpStatusCode, message); }
				var dbItem = await Repo.Get_CityAsync(cityId, numChildLevels);

				if (dbItem == null)
				{
					Log.LogWarning(eventId: (int)coreEnums.EventId.Warn_WebApi,
						message: "Unable to get object via Web API for RequestUri {{RequestUri}}",
						Request.RequestUri.ToString());

					return NotFound();
				}

				RunCustomLogicOnGetEntityByPK(ref dbItem, cityId, numChildLevels);
				return Ok(_factory.Create(dbItem));
			}
			catch (Exception ex)
			{
				Log.LogError(eventId: (int)coreEnums.EventId.Exception_WebApi,
					exception: ex,
					message: "Unable to get object by PK via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}

		[HttpPatch]
		[VersionedRoute(template: "Cities/{cityId}", allowedVersion: 1)]
		public async Task<IHttpActionResult> Patch(Guid cityId, [FromBody] JsonPatchDocument<dtoCSC.City> patchDocument)
		{
			try
			{
				if (!base.OnActionExecuting(out HttpStatusCode httpStatusCode, out string message)) { return Content(httpStatusCode, message); }

				if (patchDocument == null)
				{
					return BadRequest();
				}

				var dbItem = await Repo.Get_CityAsync(cityId, numChildLevels: 0);
				if (dbItem == null)
				{
					return NotFound();
				}

				var dtoItem = _factory.Create(dbItem); // map

				// apply changes to the DTO
				patchDocument.ApplyTo(dtoItem);
				dtoItem.CityId = cityId;

				// map the DTO with applied changes to the entity, & update
				var updatedDBItem = _factory.Create(dtoItem); // map
				var result = await Repo.UpdateAsync(updatedDBItem);
				RunCustomLogicAfterUpdatePatch(ref updatedDBItem, ref result);

				if (result.Status == cghEnums.RepositoryActionStatus.Updated)
				{
					// map to dto
					var patchedDTOItem = _factory.Create(result.Entity);
					return Ok(patchedDTOItem);
				}

				Log.LogWarning(eventId: (int)coreEnums.EventId.Warn_WebApi,
					exception: result.Exception,
					message: "Unable to patch object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				return BadRequest();
			}
			catch (Exception ex)
			{
				Log.LogError(eventId: (int)coreEnums.EventId.Exception_WebApi,
					exception: ex,
					message: "Unable to patch object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}

		[HttpPost]
		[VersionedRoute(template: "Cities", allowedVersion: 1)]
		public async Task<IHttpActionResult> Post([FromBody] dtoCSC.City dtoItem)
		{
			try
			{
				if (!base.OnActionExecuting(out HttpStatusCode httpStatusCode, out string message)) { return Content(httpStatusCode, message); }

				if (dtoItem == null)
				{
					return BadRequest();
				}

				// try mapping & saving
				var newDBItem = _factory.Create(dtoItem);

				var result = await Repo.InsertAsync(newDBItem);
				RunCustomLogicAfterInsert(ref newDBItem, ref result);

				if (result.Status == cghEnums.RepositoryActionStatus.Created)
				{   // map to dto
					var newDTOItem = _factory.Create(result.Entity);
					var uriFormatted = Request.RequestUri.ToString().EndsWith("/") == true ? Request.RequestUri.ToString().Substring(0, Request.RequestUri.ToString().Length - 1) : Request.RequestUri.ToString();
					return Created($"{uriFormatted}/{newDTOItem.CityId}", newDTOItem);
				}

				Log.LogWarning(eventId: (int)coreEnums.EventId.Warn_WebApi,
					exception: result.Exception,
					message: "Unable to create object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				return BadRequest();
			}
			catch (Exception ex)
			{
				Log.LogError(eventId: (int)coreEnums.EventId.Exception_WebApi,
					exception: ex,
					message: "Unable to create object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());


				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}

		[HttpPut]
		[VersionedRoute(template: "Cities/{cityId}", allowedVersion: 1)]
		public async Task<IHttpActionResult> Put(Guid cityId, [FromBody] dtoCSC.City dtoItem)
		{
			try
			{
				if (!base.OnActionExecuting(out HttpStatusCode httpStatusCode, out string message)) { return Content(httpStatusCode, message); }

				if (dtoItem == null)
				{
					return BadRequest();
				}

				dtoItem.CityId = cityId;

				var updatedDBItem = _factory.Create(dtoItem); // map
				RunCustomLogicBeforeUpdatePut(ref updatedDBItem, cityId);
				var result = await Repo.UpdateAsync(updatedDBItem);
				RunCustomLogicAfterUpdatePut(ref updatedDBItem, ref result);

				if (result.Status == cghEnums.RepositoryActionStatus.Updated)
				{
					// map to dto
					var updatedDTOItem = _factory.Create(result.Entity);
					return Ok(updatedDTOItem);
				}
				else if (result.Status == cghEnums.RepositoryActionStatus.NotFound)
				{
					return NotFound();
				}

				Log.LogWarning(eventId: (int)coreEnums.EventId.Warn_WebApi,
					exception: result.Exception,
					message: "Unable to update object via Web API for RequestUri {{RequestUri}}", 
					Request.RequestUri.ToString());

				return BadRequest();
			}
			catch (Exception ex)
			{
				Log.LogError(eventId: (int)coreEnums.EventId.Exception_WebApi,
					exception: ex,
					message: "Unable to update object via Web API for RequestUri {{RequestUri}}",
					Request.RequestUri.ToString());

				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}

		partial void RunCustomLogicAfterInsert(ref entCSC.City newDBItem, ref IRepositoryActionResult<entCSC.City> result);

		partial void RunCustomLogicAfterUpdatePatch(ref entCSC.City updatedDBItem, ref IRepositoryActionResult<entCSC.City> result);

		partial void RunCustomLogicAfterUpdatePut(ref entCSC.City updatedDBItem, ref IRepositoryActionResult<entCSC.City> result);

		partial void RunCustomLogicBeforeUpdatePut(ref entCSC.City updatedDBItem, Guid cityId);

		partial void RunCustomLogicOnGetEntityByPK(ref entCSC.City dbItem, Guid cityId, int numChildLevels);

		partial void RunCustomLogicAfterGetQueryableList(ref IQueryable<entCSC.City> dbItems, ref List<string> filterList);
	}
}