// <auto-generated> - Template:RepositoryInterface, Version:2.0, Id:c31289e3-93da-4fdf-ba45-05bc7bcf9204
using CodeGenHero.Repository;
using CGHClientServer1.DB.Entities;
using System;
using System.Threading.Tasks;

namespace CGHClientServer1.Repository.Interface
{
	public partial interface ICSCRepository : ICSCRepositoryCrud
	{

		CountryStateCityDbContext CountryStateCityDbContext { get; }

		Task<IRepositoryActionResult<City>> Delete_CityAsync(Guid cityId);
		Task<City> Get_CityAsync(Guid cityId, int numChildLevels);

		Task<IRepositoryActionResult<Country>> Delete_CountryAsync(Guid countryId);
		Task<Country> Get_CountryAsync(Guid countryId, int numChildLevels);

		Task<IRepositoryActionResult<State>> Delete_StateAsync(Guid stateId);
		Task<State> Get_StateAsync(Guid stateId, int numChildLevels);

	}
}
