// <auto-generated> - Template:RepositoryInterfaceCrud, Version:2.0, Id:387dfdc5-b9f2-4ab4-accb-00a22cdd916c
using CodeGenHero.Repository;
using CGHClientServer1.DB.Entities;
using System.Linq;

namespace CGHClientServer1.Repository.Interface
{
	public interface ICSCRepositoryCrud : 
		ICRUDOperation<City>,
		ICRUDOperation<Country>,
		ICRUDOperation<State>
	{

		#region GetQueryable

		IQueryable<City> GetQueryable_City();
		IQueryable<Country> GetQueryable_Country();
		IQueryable<State> GetQueryable_State();

		#endregion

	}
}
