// <auto-generated> - Template:Repository, Version:2.0, Id:1cf6c29c-c8cf-4620-85d8-9122c2c05091
using CGHClientServer1.DB.Entities;
using CGHClientServer1.Repository.Interface;
using System;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace CGHClientServer1.Repository
{
	public partial class CSCRepository : CSCRepositoryBase, ICSCRepository
	{
		public CSCRepository(CountryStateCityDbContext ctx) : base(ctx)
		{
		}

		public CountryStateCityDbContext CountryStateCityDbContext { get { return DbContext; } }
	}
}
