// <auto-generated> - Template:WebApiControllerPartialMethods, Version:2.0, Id:0aea3751-020a-4f50-93e5-0c58a2c8e953
using CodeGenHero.Repository;
using entCSC = CGHClientServer1.DB.Entities;

namespace CGHClientServer1.API.Controllers.CSC
{
	public partial class StatesCSCController : CSCBaseApiController
	{

		//partial void RunCustomLogicAfterInsert(ref entCSC.State newDBItem, ref IRepositoryActionResult<entCSC.State> result) {}

		//partial void RunCustomLogicAfterUpdatePatch(ref entCSC.State updatedDBItem, ref IRepositoryActionResult<entCSC.State> result) {}

		partial void RunCustomLogicAfterUpdatePut(ref entCSC.State updatedDBItem, ref IRepositoryActionResult<entCSC.State> result)
		{
			if (result.Status == Enums.RepositoryActionStatus.NotFound)
			{	// An update/PUT was attempted when it should have been a create/POST.
				var localDBItem = updatedDBItem;
				var insertResult = RunSync<IRepositoryActionResult<entCSC.State>>(() => Repo.InsertAsync(localDBItem));
				if (insertResult.Status == Enums.RepositoryActionStatus.Created)
				{   // Insert worked
					result = new RepositoryActionResult<entCSC.State>(insertResult.Entity, Enums.RepositoryActionStatus.Updated);
				}
			}
		}

		// partial void RunCustomLogicBeforeUpdatePut(ref entCSC.State updatedDBItem, Guid stateId)
		// {
		// 	var existingDBItem = Utils.AsyncHelper.RunSync<entCSC.State>(() => Repo.Get_StateAsync(stateId, 1));
		// 	if (existingDBItem != null)
		// 	{	// Do not allow the user to change the "MySpecialField" value.
		// 		updatedDBItem.MySpecialField = existingDBItem.MySpecialField;
		// 	}
		// }

		///// <summary>
		///// A sample implementation of custom logic used to either manipulate a DTO item or include related entities.
		///// </summary>
		///// <param name="dbItem"></param>
		///// <param name="id"></param>
		///// <param name="numChildLevels"></param>
		// partial void RunCustomLogicOnGetEntityByPK(ref entCSC.State dbItem, Guid stateId, int numChildLevels)
		// {
			// if (numChildLevels > 1)
			// {
				// int[] orderLineItemIds = dbItem.OrderLineItems.Select(x => x.OrderLineItemId).ToArray();

				// var lineItemDiscounts = Repo.CountryStateCityDbContext.OrderLineItemDiscounts.Where(x => orderLineItemIds.Contains(x.OrderLineItemId)).ToList();

				// foreach (var lineItemDiscount in lineItemDiscounts)
				// { // Find the match and add the item to it.
					// var orderLineItem = dbItem.OrderLineItems.Where(x => x.OrderLineItemId == lineItemDiscount.OrderLineItemId).FirstOrDefault();

					// if (orderLineItem == null)
					// {
						// throw new Microsoft.EntityFrameworkCore.ObjectNotFoundException($"Unable to locate matching OrderLineItem record for {lineItemDiscount.OrderLineItemId}."
					// }

					// orderLineItem.LineItemDiscounts.Add(lineItemDiscount);
				// }
			// }

		// }

		///// <summary>
		///// A sample implementation of custom logic used to filter on a field that exists in a related, parent, table.
		///// </summary>
		///// <param name="dbItems"></param>
		///// <param name="filterList"></param>
		//partial void RunCustomLogicAfterGetQueryableList(ref IQueryable<entCSC.State> dbItems, ref List<string> filterList)
		//{
		//	var queryableFilters = filterList.ToQueryableFilter();
		//	var myFilterCriterion = queryableFilters.Where(y => y.Member.ToLowerInvariant() == "<myFieldName>").FirstOrDefault(); // Examine the incoming filter for the presence of a field name which does not exist on the target entity.

		//	if (myFilterCriterion != null)
		//	{   // myFieldName is a criterion that has to be evaluated at a level other than our target entity.
		//		dbItems = dbItems.Include(x => x.myFKRelatedEntity).Where(x => x.myFKRelatedEntity.myFieldName == new Guid(myFilterCriterion.Value));
		//		queryableFilters.Remove(myFilterCriterion);  // The evaluated criterion needs to be removed from the list of filters before we invoke the ApplyFilter() extension method.
		//		filterList = queryableFilters.ToQueryableStringList();
		//	}
		//}
	}
}
